import type { DesignBreakdown } from "./types";

// Pre-curated item breakdowns for selected mock designs.
// Each entry describes furniture/decor found in the image along with similar product links.
export const designBreakdowns: DesignBreakdown[] = [
  {
    designId: "design-1",
    items: [
      {
        category: "sofa",
        title: "Minimal beige sofa with light wood legs",
        style: "scandinavian",
        palette: "neutral",
        material: "textile + wood",
        similarity: 0.92,
        link1: "https://www.ikea.com/us/en/p/friheten-sleeper-sectional-sofa-hyllie-beige-s09340326/",
        link2: "https://www.wayfair.com/furniture/pdp/mercury-row-heard-sofa-w002913158.html",
      },
      {
        category: "armchair",
        title: "Rounded accent chair in beige",
        style: "scandinavian",
        palette: "warm",
        material: "textile + wood",
        similarity: 0.9,
        link1: "https://www.ikea.com/us/en/p/vedbo-armchair-gunnared-beige-80384158/",
        link2: "https://www.amazon.com/dp/B09CHMKM33",
      },
      {
        category: "floor lamp",
        title: "Tall metal floor lamp with warm tone shade",
        style: "modern",
        palette: "warm",
        material: "metal",
        similarity: 0.86,
        link1: "https://www.leroymerlin.ru/product/torser-napolnyy-81953126/",
      },
      {
        category: "rug",
        title: "Beige cotton rug with subtle geometric texture",
        style: "boho",
        palette: "neutral",
        material: "textile",
        similarity: 0.85,
        link1: "https://www.amazon.com/dp/B079G1ZG1L",
        link2: "https://www.zarahome.com/us/textile/rugs/",
      },
      {
        category: "coffee table",
        title: "Low round coffee table, light wood",
        style: "minimal",
        palette: "neutral",
        material: "wood",
        similarity: 0.84,
        link1: "https://www.ikea.com/us/en/p/lack-coffee-table-white-70449904/",
      },
      {
        category: "plants",
        title: "Potted green plant",
        style: "boho",
        palette: "green",
        material: "ceramic + foliage",
        similarity: 0.8,
        link1: "https://www.ikea.com/us/en/p/fejka-artificial-potted-plant-indoor-outdoor-monstera-90349547/",
      },
    ],
  },
  {
    designId: "design-2",
    items: [
      {
        category: "balcony set",
        title: "Metal balcony chairs with slim profile",
        style: "modern",
        palette: "cool",
        material: "metal",
        similarity: 0.88,
        link1: "https://www.amazon.com/dp/B0B2JVP3KH",
      },
      {
        category: "side table",
        title: "Compact round side table, black metal",
        style: "minimal",
        palette: "neutral",
        material: "metal",
        similarity: 0.85,
        link1: "https://www.ikea.com/us/en/p/gladom-tray-table-black-30411990/",
      },
      {
        category: "planter",
        title: "Tall planter with green foliage",
        style: "modern",
        palette: "green",
        material: "ceramic",
        similarity: 0.82,
        link1: "https://www.zarahome.com/us/garden/",
      },
      {
        category: "rug",
        title: "Outdoor neutral flatweave rug",
        style: "minimal",
        palette: "neutral",
        material: "polypropylene",
        similarity: 0.8,
        link1: "https://www.wayfair.com/rugs/pdp/outdoor-neutral-flatweave-rug-w007860058.html",
      },
    ],
  },
  {
    designId: "design-3",
    items: [
      {
        category: "sofa",
        title: "Charcoal modern sectional",
        style: "industrial",
        palette: "neutral",
        material: "textile",
        similarity: 0.9,
        link1: "https://www.article.com/product/sofa",
      },
      {
        category: "coffee table",
        title: "Concrete-look coffee table",
        style: "industrial",
        palette: "grey",
        material: "concrete",
        similarity: 0.87,
        link1: "https://www.ikea.com/us/en/p/listerby-coffee-table-dark-brown-10449912/",
      },
      {
        category: "wall art",
        title: "Black and white abstract prints",
        style: "modern",
        palette: "monochrome",
        material: "paper + frame",
        similarity: 0.82,
        link1: "https://www.amazon.com/dp/B08XN8X2PR",
      },
      {
        category: "flooring",
        title: "Exposed concrete floor",
        style: "industrial",
        palette: "neutral",
        material: "concrete",
        similarity: 0.95,
      },
      {
        category: "shelves",
        title: "Open metal shelving",
        style: "industrial",
        palette: "black",
        material: "metal",
        similarity: 0.84,
        link1: "https://www.ikea.com/us/en/p/omar-shelving-unit-galvanized-00267575/",
      },
    ],
  },
  {
    designId: "design-4",
    items: [
      {
        category: "bed",
        title: "Low-profile bed with layered textiles",
        style: "boho",
        palette: "warm",
        material: "fabric + wood",
        similarity: 0.9,
        link1: "https://www.ikea.com/us/en/p/nyvoll-bed-frame-brown-stained-ash-veneer-lur%C3%B6y-s89170393/",
      },
      {
        category: "rug",
        title: "Thick textured rug, warm brown",
        style: "boho",
        palette: "warm",
        material: "textile",
        similarity: 0.86,
        link1: "https://www.amazon.com/dp/B07R6V9Y6L",
      },
      {
        category: "lighting",
        title: "Soft bedside lamp with fabric shade",
        style: "boho",
        palette: "warm",
        material: "textile + wood",
        similarity: 0.82,
        link1: "https://www.ikea.com/us/en/p/lampan-table-lamp-white-60316540/",
      },
      {
        category: "plants",
        title: "Cluster of indoor plants",
        style: "boho",
        palette: "green",
        material: "foliage",
        similarity: 0.8,
        link1: "https://www.ikea.com/us/en/p/fejka-artificial-potted-plant-90486385/",
      },
    ],
  },
  {
    designId: "design-5",
    items: [
      {
        category: "kitchen cabinets",
        title: "Flat-panel white kitchen with wood accents",
        style: "scandinavian",
        palette: "cool",
        material: "wood + laminate",
        similarity: 0.93,
      },
      {
        category: "dining table",
        title: "Light wood dining table",
        style: "minimal",
        palette: "neutral",
        material: "wood",
        similarity: 0.88,
        link1: "https://www.ikea.com/us/en/p/lisabo-table-ash-veneer-30365726/",
      },
      {
        category: "dining chairs",
        title: "White molded dining chairs",
        style: "scandinavian",
        palette: "cool",
        material: "plastic + wood",
        similarity: 0.87,
        link1: "https://www.amazon.com/dp/B07MZPG5G3",
      },
      {
        category: "pendant lights",
        title: "Simple white pendants over island",
        style: "minimal",
        palette: "cool",
        material: "metal",
        similarity: 0.85,
        link1: "https://www.leroymerlin.ru/product/lyustra-81423123/",
      },
      {
        category: "bar stools",
        title: "Wood and white bar stools",
        style: "scandinavian",
        palette: "neutral",
        material: "wood + plastic",
        similarity: 0.84,
        link1: "https://www.ikea.com/us/en/p/dalfred-bar-stool-black-50246089/",
      },
    ],
  },
];
