import type { DesignBreakdown } from "./types";

export const designBreakdowns: DesignBreakdown[] = [
  {
    designId: "design-1",
    summary:
      "Скандинавская гостиная с тёплой нейтральной палитрой, светлым деревом и мягким рассеянным светом. Акцент на диване и кофейном столике, вокруг которых собрана композиция.",
    difficulty: "easy",
    mainStyle: "scandinavian",
    keyPoints: [
      "Тёплый беж + светлое дерево = уют без перегруза",
      "Минимум декора, максимум воздуха",
      "Мягкий текстиль + один выразительный торшер",
    ],
    items: [
      {
        id: "d1-sofa",
        category: "sofa",
        role: "primary",
        title: "Beige 3-seater Scandinavian sofa",
        description:
          "Главный якорь: прямые линии, светлые ножки, нейтральная ткань. Формирует посадочную зону.",
        style: "scandinavian",
        palette: "warm neutral",
        material: "textile + light wood",
        importance: 1,
        zone: "seating",
        notes: [
          "Высота сиденья 42–45 см",
          "Ножки светлое дерево, без резьбы",
        ],
        products: [
          {
            shop: "IKEA",
            title: "FRIHETEN beige",
            url: "https://www.ikea.com/us/en/p/friheten-sleeper-sectional-sofa-hyllie-beige-s09340326/",
            similarity: 0.92,
            note: "very close match",
          },
          {
            shop: "Wayfair",
            title: "Heard Sofa",
            url: "https://www.wayfair.com/furniture/pdp/mercury-row-heard-sofa-w002913158.html",
            similarity: 0.86,
            note: "budget",
          },
        ],
      },
      {
        id: "d1-chair",
        category: "armchair",
        role: "secondary",
        title: "Rounded accent chair in beige",
        description:
          "Смягчает углы композиции, добавляет объём и дополнительную посадку.",
        style: "scandinavian",
        palette: "warm",
        material: "textile + wood",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "VEDBO armchair",
            url: "https://www.ikea.com/us/en/p/vedbo-armchair-gunnared-beige-80384158/",
            similarity: 0.9,
            note: "close match",
          },
          {
            shop: "Amazon",
            title: "Beige accent chair",
            url: "https://www.amazon.com/dp/B09CHMKM33",
            similarity: 0.82,
            note: "budget option",
          },
        ],
      },
      {
        id: "d1-coffee",
        category: "coffee_table",
        role: "secondary",
        title: "Low round coffee table, light wood",
        description:
          "Компактный столик без лишних деталей, поддерживает светлую палитру.",
        style: "minimal",
        palette: "neutral",
        material: "wood",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "LACK coffee table",
            url: "https://www.ikea.com/us/en/p/lack-coffee-table-white-70449904/",
            similarity: 0.84,
          },
        ],
      },
      {
        id: "d1-rug",
        category: "rug",
        role: "secondary",
        title: "Beige cotton rug with texture",
        description:
          "Объединяет посадочную зону, добавляет теплоты и тактильности.",
        style: "boho",
        palette: "neutral",
        material: "textile",
        importance: 2,
        zone: "textiles",
        products: [
          {
            shop: "Amazon",
            title: "Textured beige rug",
            url: "https://www.amazon.com/dp/B079G1ZG1L",
            similarity: 0.85,
            note: "close match",
          },
          {
            shop: "Zara Home",
            title: "Neutral cotton rug",
            url: "https://www.zarahome.com/us/textile/rugs/",
            similarity: 0.8,
          },
        ],
      },
      {
        id: "d1-lamp",
        category: "floor_lamp",
        role: "accent",
        title: "Tall metal floor lamp, warm glow",
        description:
          "Создаёт мягкий акцентный свет, подчёркивает текстуры в вечернее время.",
        style: "modern",
        palette: "warm",
        material: "metal",
        importance: 3,
        zone: "lighting",
        products: [
          {
            shop: "Leroy Merlin",
            title: "Metal floor lamp",
            url: "https://www.leroymerlin.ru/product/torser-napolnyy-81953126/",
            similarity: 0.86,
          },
        ],
      },
      {
        id: "d1-plant",
        category: "decor",
        role: "accent",
        title: "Potted green plant",
        description:
          "Живой акцент, добавляет цвет и свежесть, балансирует тёплые тона.",
        style: "boho",
        palette: "green",
        material: "ceramic + foliage",
        importance: 3,
        zone: "decor",
        products: [
          {
            shop: "IKEA",
            title: "FEJKA monstera",
            url: "https://www.ikea.com/us/en/p/fejka-artificial-potted-plant-indoor-outdoor-monstera-90349547/",
            similarity: 0.8,
          },
        ],
      },
    ],
  },
  {
    designId: "design-2",
    summary:
      "Минималистичный балкон с прохладной палитрой и лёгкой мебелью. Чистые линии и компактные предметы дают ощущение аккуратного outdoor-уголка.",
    difficulty: "easy",
    mainStyle: "minimal",
    keyPoints: [
      "Металл + холодные тона = лаконично",
      "Всё легко переносится и чистится",
      "Растение смягчает жёсткие линии",
    ],
    items: [
      {
        id: "d2-chairs",
        category: "chair",
        role: "primary",
        title: "Slim metal balcony chairs",
        description:
          "Лёгкие складные кресла с лаконичным силуэтом, не загромождают пространство.",
        style: "modern",
        palette: "cool",
        material: "metal",
        importance: 1,
        zone: "seating",
        products: [
          {
            shop: "Amazon",
            title: "Outdoor metal chairs set",
            url: "https://www.amazon.com/dp/B0B2JVP3KH",
            similarity: 0.88,
            note: "close match",
          },
        ],
      },
      {
        id: "d2-table",
        category: "side_table",
        role: "secondary",
        title: "Compact round side table",
        description: "Небольшой столик для напитков и декора, чёрный металл.",
        style: "minimal",
        palette: "neutral",
        material: "metal",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "GLADOM tray table",
            url: "https://www.ikea.com/us/en/p/gladom-tray-table-black-30411990/",
            similarity: 0.85,
          },
        ],
      },
      {
        id: "d2-plant",
        category: "planter",
        role: "accent",
        title: "Tall planter with foliage",
        description:
          "Вертикальный акцент, вносит зелёный цвет и разбивает монохром.",
        style: "modern",
        palette: "green",
        material: "ceramic",
        importance: 3,
        zone: "decor",
        products: [
          {
            shop: "Zara Home",
            title: "Stone planter",
            url: "https://www.zarahome.com/us/garden/",
            similarity: 0.82,
          },
        ],
      },
      {
        id: "d2-rug",
        category: "rug",
        role: "secondary",
        title: "Outdoor flatweave rug",
        description:
          "Добавляет уют и разделяет зону, оставаясь устойчивым к улице.",
        style: "minimal",
        palette: "neutral",
        material: "polypropylene",
        importance: 2,
        zone: "textiles",
        products: [
          {
            shop: "Wayfair",
            title: "Outdoor neutral rug",
            url: "https://www.wayfair.com/rugs/pdp/outdoor-neutral-flatweave-rug-w007860058.html",
            similarity: 0.8,
          },
        ],
      },
    ],
  },
  {
    designId: "design-3",
    summary:
      "Индастриал-гостиная с бетонными поверхностями и тёмным текстилем. Основные акценты — секционный диван и бетонный столик.",
    difficulty: "medium",
    mainStyle: "industrial",
    keyPoints: [
      "Серый текстиль + бетон = индустриальный характер",
      "Открытые металлоконструкции вместо закрытого хранения",
      "Чёрно-белый арт поддерживает монохром",
    ],
    items: [
      {
        id: "d3-sofa",
        category: "sofa",
        role: "primary",
        title: "Charcoal sectional sofa",
        description:
          "Основная посадка, тёмный цвет подчёркивает индустриальную палитру.",
        style: "industrial",
        palette: "neutral",
        material: "textile",
        importance: 1,
        zone: "seating",
        products: [
          {
            shop: "Article",
            title: "Charcoal sectional",
            url: "https://www.article.com/product/sofa",
            similarity: 0.9,
          },
        ],
      },
      {
        id: "d3-coffee",
        category: "coffee_table",
        role: "secondary",
        title: "Concrete-look coffee table",
        description:
          "Усиливает бетонный характер, низкий профиль, строгие линии.",
        style: "industrial",
        palette: "grey",
        material: "concrete",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "LISTERBY",
            url: "https://www.ikea.com/us/en/p/listerby-coffee-table-dark-brown-10449912/",
            similarity: 0.87,
          },
        ],
      },
      {
        id: "d3-art",
        category: "wall_art",
        role: "accent",
        title: "Black & white abstract prints",
        description:
          "Даёт фокус на стене, поддерживает монохром и ритм вертикалей.",
        style: "modern",
        palette: "monochrome",
        material: "paper + frame",
        importance: 3,
        zone: "decor",
        products: [
          {
            shop: "Amazon",
            title: "Abstract set of 3",
            url: "https://www.amazon.com/dp/B08XN8X2PR",
            similarity: 0.82,
          },
        ],
      },
      {
        id: "d3-shelf",
        category: "shelves",
        role: "secondary",
        title: "Open metal shelving",
        description:
          "Хранение без фасадов, подчёркивает индустриальный стиль.",
        style: "industrial",
        palette: "black",
        material: "metal",
        importance: 2,
        zone: "storage",
        products: [
          {
            shop: "IKEA",
            title: "OMAR shelving unit",
            url: "https://www.ikea.com/us/en/p/omar-shelving-unit-galvanized-00267575/",
            similarity: 0.84,
          },
        ],
      },
      {
        id: "d3-floor",
        category: "flooring",
        role: "primary",
        title: "Exposed concrete floor",
        description:
          "Базовая текстура интерьера, ключевой носитель индустриального настроения.",
        style: "industrial",
        palette: "neutral",
        material: "concrete",
        importance: 1,
        zone: "storage",
        products: [],
      },
    ],
  },
  {
    designId: "design-4",
    summary:
      "Бохо-спальня с мягким светом и множеством текстур. Слойность текстиля создаёт расслабленное настроение.",
    difficulty: "easy",
    mainStyle: "boho",
    keyPoints: [
      "Слойность покрывал и подушек",
      "Тёплая палитра, приглушённый свет",
      "Растения и плетёный декор для органики",
    ],
    items: [
      {
        id: "d4-bed",
        category: "bed",
        role: "primary",
        title: "Low-profile bed with layered textiles",
        description:
          "Основа спальни: низкое изголовье, много текстиля, тёплые тона.",
        style: "boho",
        palette: "warm",
        material: "fabric + wood",
        importance: 1,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "NYVOLL bed frame",
            url: "https://www.ikea.com/us/en/p/nyvoll-bed-frame-brown-stained-ash-veneer-lur%C3%B6y-s89170393/",
            similarity: 0.9,
          },
        ],
      },
      {
        id: "d4-rug",
        category: "rug",
        role: "secondary",
        title: "Textured brown rug",
        description:
          "Добавляет тепло и мягкость, поддерживает палитру постельного белья.",
        style: "boho",
        palette: "warm",
        material: "textile",
        importance: 2,
        zone: "textiles",
        products: [
          {
            shop: "Amazon",
            title: "Thick textured rug",
            url: "https://www.amazon.com/dp/B07R6V9Y6L",
            similarity: 0.86,
          },
        ],
      },
      {
        id: "d4-lamp",
        category: "table_lamp",
        role: "accent",
        title: "Soft bedside lamp",
        description:
          "Тёплое пятно света, уютный сценарий для чтения, текстильный абажур.",
        style: "boho",
        palette: "warm",
        material: "textile + wood",
        importance: 3,
        zone: "lighting",
        products: [
          {
            shop: "IKEA",
            title: "LAMPAN white",
            url: "https://www.ikea.com/us/en/p/lampan-table-lamp-white-60316540/",
            similarity: 0.82,
          },
        ],
      },
      {
        id: "d4-plants",
        category: "decor",
        role: "accent",
        title: "Cluster of indoor plants",
        description:
          "Органика и цвет, снимает монотонность тёплых тонов, оживляет угол.",
        style: "boho",
        palette: "green",
        material: "foliage",
        importance: 3,
        zone: "decor",
        products: [
          {
            shop: "IKEA",
            title: "FEJKA assorted",
            url: "https://www.ikea.com/us/en/p/fejka-artificial-potted-plant-90486385/",
            similarity: 0.8,
          },
        ],
      },
    ],
  },
  {
    designId: "design-5",
    summary:
      "Скандинавская кухня: белые плоскости, светлое дерево, аккуратные подвесы. Чистая геометрия и много света.",
    difficulty: "medium",
    mainStyle: "scandinavian",
    keyPoints: [
      "Белые фасады + дерево = базовая формула scandi",
      "Подвесы над островом для зонального света",
      "Стулья и барные — одинаковая палитра",
    ],
    items: [
      {
        id: "d5-cabinets",
        category: "cabinets",
        role: "primary",
        title: "Flat-panel white kitchen",
        description:
          "Минимальные ручки, ровные плоскости. Основа визуальной чистоты.",
        style: "scandinavian",
        palette: "cool",
        material: "wood + laminate",
        importance: 1,
        zone: "storage",
        products: [],
      },
      {
        id: "d5-table",
        category: "dining_table",
        role: "primary",
        title: "Light wood dining table",
        description:
          "Лёгкий стол на прямых ножках, поддерживает текстуру пола.",
        style: "minimal",
        palette: "neutral",
        material: "wood",
        importance: 1,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "LISABO table",
            url: "https://www.ikea.com/us/en/p/lisabo-table-ash-veneer-30365726/",
            similarity: 0.88,
          },
        ],
      },
      {
        id: "d5-chairs",
        category: "chair",
        role: "secondary",
        title: "White molded dining chairs",
        description:
          "Современный силуэт, белый пластик со светлым деревом, поддерживает фасады.",
        style: "scandinavian",
        palette: "cool",
        material: "plastic + wood",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "Amazon",
            title: "Set of molded chairs",
            url: "https://www.amazon.com/dp/B07MZPG5G3",
            similarity: 0.87,
          },
        ],
      },
      {
        id: "d5-pendants",
        category: "pendant",
        role: "accent",
        title: "Simple white pendants",
        description:
          "Чистая геометрия, зональный свет над столом/островом, поддержка белых фасадов.",
        style: "minimal",
        palette: "cool",
        material: "metal",
        importance: 3,
        zone: "lighting",
        products: [
          {
            shop: "Leroy Merlin",
            title: "White pendant",
            url: "https://www.leroymerlin.ru/product/lyustra-81423123/",
            similarity: 0.85,
          },
        ],
      },
      {
        id: "d5-stools",
        category: "bar_stool",
        role: "secondary",
        title: "Wood and white bar stools",
        description:
          "Повторяют палитру стульев, визуально объединяют стол и остров.",
        style: "scandinavian",
        palette: "neutral",
        material: "wood + plastic",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "DALFRED bar stool",
            url: "https://www.ikea.com/us/en/p/dalfred-bar-stool-black-50246089/",
            similarity: 0.84,
          },
        ],
      },
    ],
  },
  {
    designId: "design-6",
    summary:
      "Ретро-кабинет с тёплым деревом и винтажным настроением. Основной акцент — письменный стол и кресло.",
    difficulty: "medium",
    mainStyle: "retro",
    keyPoints: [
      "Тёплое дерево + мягкий свет",
      "Минимум техники на виду",
      "Картины/постеры для винтажного настроения",
    ],
    items: [
      {
        id: "d6-desk",
        category: "desk",
        role: "primary",
        title: "Mid-century wood desk",
        description:
          "Рабочая поверхность с тонкими ножками, тёплый шпон. Ключевой предмет кабинета.",
        style: "retro",
        palette: "neutral",
        material: "wood",
        importance: 1,
        zone: "storage",
        products: [
          {
            shop: "Wayfair",
            title: "Mid-century desk",
            url: "https://www.wayfair.com/furniture/pdp/mid-century-desk-w005404986.html",
            similarity: 0.83,
          },
        ],
      },
      {
        id: "d6-chair",
        category: "chair",
        role: "secondary",
        title: "Upholstered office chair, warm brown",
        description:
          "Мягкая посадка, поддерживает палитру стола, добавляет винтажного ощущения.",
        style: "retro",
        palette: "warm",
        material: "textile + wood",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "Amazon",
            title: "Retro office chair",
            url: "https://www.amazon.com/dp/B08QZKL9RB",
            similarity: 0.81,
          },
        ],
      },
      {
        id: "d6-lamp",
        category: "desk_lamp",
        role: "accent",
        title: "Compact desk lamp",
        description:
          "Локальный свет, подчёркивает рабочую область, поддерживает ретро.",
        style: "retro",
        palette: "warm",
        material: "metal",
        importance: 3,
        zone: "lighting",
        products: [
          {
            shop: "IKEA",
            title: "TERTIAL work lamp",
            url: "https://www.ikea.com/us/en/p/tertial-work-lamp-dark-gray-50355395/",
            similarity: 0.82,
          },
        ],
      },
      {
        id: "d6-art",
        category: "wall_art",
        role: "accent",
        title: "Vintage posters",
        description:
          "Заполняют стену, добавляют характер и графику без перегруза.",
        style: "retro",
        palette: "neutral",
        material: "paper + frame",
        importance: 3,
        zone: "decor",
        products: [
          {
            shop: "Amazon",
            title: "Retro wall art set",
            url: "https://www.amazon.com/dp/B0B8RW8XP7",
            similarity: 0.8,
          },
        ],
      },
    ],
  },
  {
    designId: "design-7",
    summary:
      "Япанди-спальня: нейтральная палитра, светлое дерево, минимум предметов. Спокойствие и порядок.",
    difficulty: "easy",
    mainStyle: "japandi",
    keyPoints: [
      "Низкая мебель + горизонтали",
      "Нейтральные тона, фактура дерева",
      "Мало декора, чистые линии",
    ],
    items: [
      {
        id: "d7-bed",
        category: "bed",
        role: "primary",
        title: "Low japandi bed",
        description:
          "Минимальное изголовье, светлое дерево, лёгкий текстиль. Центр спальни.",
        style: "japandi",
        palette: "neutral",
        material: "wood + textile",
        importance: 1,
        zone: "seating",
        products: [
          {
            shop: "IKEA",
            title: "BJÖRKSNÄS bed",
            url: "https://www.ikea.com/us/en/p/bjoerksnaes-bed-frame-birch-luroey-80439494/",
            similarity: 0.85,
          },
        ],
      },
      {
        id: "d7-nightstand",
        category: "nightstand",
        role: "secondary",
        title: "Light wood nightstand",
        description:
          "Простой куб, минимум фурнитуры. Поддерживает горизонталь кровати.",
        style: "japandi",
        palette: "neutral",
        material: "wood",
        importance: 2,
        zone: "storage",
        products: [
          {
            shop: "Wayfair",
            title: "Minimal nightstand",
            url: "https://www.wayfair.com/furniture/pdp/minimal-nightstand-w005930351.html",
            similarity: 0.82,
          },
        ],
      },
      {
        id: "d7-lamp",
        category: "table_lamp",
        role: "accent",
        title: "Warm bedside lamp",
        description:
          "Низкий тёплый свет, рисует уютный сценарий, не забирает внимание.",
        style: "japandi",
        palette: "warm",
        material: "paper + wood",
        importance: 3,
        zone: "lighting",
        products: [
          {
            shop: "IKEA",
            title: "TOKABO",
            url: "https://www.ikea.com/us/en/p/tokabo-table-lamp-white-50502084/",
            similarity: 0.83,
          },
        ],
      },
      {
        id: "d7-rug",
        category: "rug",
        role: "secondary",
        title: "Neutral flatweave rug",
        description:
          "Мягкая подложка, добавляет текстуры, остаётся незаметной.",
        style: "minimal",
        palette: "neutral",
        material: "textile",
        importance: 2,
        zone: "textiles",
        products: [
          {
            shop: "Amazon",
            title: "Flatweave rug",
            url: "https://www.amazon.com/dp/B0BWWCLG57",
            similarity: 0.81,
          },
        ],
      },
    ],
  },
  {
    designId: "design-8",
    summary:
      "Современная ванная с белой палитрой и камнем. Светлые поверхности и стекло создают ощущение спа.",
    difficulty: "medium",
    mainStyle: "modern",
    keyPoints: [
      "Белый камень + стекло",
      "Минимум хранения на виду",
      "Тёплый свет для уюта",
    ],
    items: [
      {
        id: "d8-vanity",
        category: "vanity",
        role: "primary",
        title: "Floating stone vanity",
        description:
          "Парящая тумба без ножек, сохраняет лёгкость и подчёркивает плитку.",
        style: "modern",
        palette: "monochrome",
        material: "stone",
        importance: 1,
        zone: "storage",
        products: [],
      },
      {
        id: "d8-light",
        category: "mirror_light",
        role: "accent",
        title: "Warm mirror lighting",
        description:
          "Подсветка по периметру зеркала создаёт мягкий glow без бликов.",
        style: "modern",
        palette: "warm",
        material: "led + glass",
        importance: 3,
        zone: "lighting",
        products: [],
      },
      {
        id: "d8-accessories",
        category: "decor",
        role: "accent",
        title: "Minimal accessories",
        description:
          "Белые полотенца, дозаторы, немного зелени для контраста с камнем.",
        style: "minimal",
        palette: "neutral",
        material: "textile + glass",
        importance: 3,
        zone: "decor",
        products: [],
      },
    ],
  },
  {
    designId: "design-9",
    summary:
      "Лофт-кухня с бетонными поверхностями и открытыми полками. Холодная палитра и индустриальные акценты.",
    difficulty: "hard",
    mainStyle: "loft",
    keyPoints: [
      "Бетон + металл — характер лофта",
      "Открытые полки вместо закрытых шкафов",
      "Строгий свет, минимум декора",
    ],
    items: [
      {
        id: "d9-island",
        category: "kitchen_island",
        role: "primary",
        title: "Concrete kitchen island",
        description:
          "Бетонный блок в центре, задаёт индустриальный тон всей кухне.",
        style: "industrial",
        palette: "cool",
        material: "concrete",
        importance: 1,
        zone: "storage",
        products: [],
      },
      {
        id: "d9-shelving",
        category: "shelves",
        role: "secondary",
        title: "Open metal shelving",
        description:
          "Хранение без фасадов, подчёркивает лофт, позволяет выставить посуду.",
        style: "industrial",
        palette: "black",
        material: "metal",
        importance: 2,
        zone: "storage",
        products: [
          {
            shop: "IKEA",
            title: "OMAR open shelves",
            url: "https://www.ikea.com/us/en/p/omar-shelving-unit-galvanized-00267575/",
            similarity: 0.84,
          },
        ],
      },
      {
        id: "d9-stools",
        category: "bar_stool",
        role: "secondary",
        title: "Metal bar stools",
        description:
          "Чёрный металл, простой профиль. Поддержка индустриального настроения.",
        style: "industrial",
        palette: "dark",
        material: "metal",
        importance: 2,
        zone: "seating",
        products: [
          {
            shop: "Amazon",
            title: "Metal bar stools set",
            url: "https://www.amazon.com/dp/B07G15MP2Q",
            similarity: 0.8,
          },
        ],
      },
      {
        id: "d9-light",
        category: "pendant",
        role: "accent",
        title: "Linear industrial pendants",
        description:
          "Чёткая геометрия света над островом, чёрный металл, холодное свечение.",
        style: "industrial",
        palette: "cool",
        material: "metal",
        importance: 3,
        zone: "lighting",
        products: [],
      },
    ],
  },
  {
    designId: "design-10",
    summary:
      "Уютный уголок с плотной посадкой: мягкий диван, тёплый свет, растение. Сдержанная палитра, много текстуры.",
    difficulty: "easy",
    mainStyle: "modern",
    keyPoints: [
      "Мягкий диван + текстиль",
      "Тёплый торшер создаёт уют вечером",
      "Растение даёт живой акцент",
    ],
    items: [
      {
        id: "d10-sofa",
        category: "sofa",
        role: "primary",
        title: "Cozy chaise sofa",
        description:
          "Главный элемент посадки, обнимающая форма, текстиль средней фактуры.",
        style: "modern",
        palette: "neutral",
        material: "textile",
        importance: 1,
        zone: "seating",
        products: [],
      },
      {
        id: "d10-lamp",
        category: "floor_lamp",
        role: "accent",
        title: "Slim floor lamp",
        description:
          "Дает тёплое пятно света в зоне дивана, не перетягивает внимание.",
        style: "modern",
        palette: "warm",
        material: "metal",
        importance: 3,
        zone: "lighting",
        products: [],
      },
      {
        id: "d10-plant",
        category: "decor",
        role: "accent",
        title: "Tall indoor plant",
        description:
          "Вносит вертикаль и зелёный акцент, оживляет нейтральную палитру.",
        style: "modern",
        palette: "green",
        material: "foliage",
        importance: 3,
        zone: "decor",
        products: [],
      },
    ],
  },
  {
    designId: "design-11",
    summary:
      "Сканди-гостиная с центральной посадкой и графичными акцентами. Светлые стены, чёрные детали, много дневного света.",
    difficulty: "medium",
    mainStyle: "scandinavian",
    keyPoints: [
      "Чёрные линии в декоре и мебели",
      "Светлый текстиль + дерево",
      "Абстрактный арт для динамики",
    ],
    items: [
      {
        id: "d11-sofa",
        category: "sofa",
        role: "primary",
        title: "Light fabric sofa",
        description:
          "Базовый диван без лишних деталей, светлый текстиль, мягкая посадка.",
        style: "scandinavian",
        palette: "neutral",
        material: "textile",
        importance: 1,
        zone: "seating",
        products: [],
      },
      {
        id: "d11-table",
        category: "coffee_table",
        role: "secondary",
        title: "Black round coffee table",
        description:
          "Добавляет контраст, собирает композицию посадки, низкий профиль.",
        style: "modern",
        palette: "black",
        material: "metal",
        importance: 2,
        zone: "seating",
        products: [],
      },
      {
        id: "d11-art",
        category: "wall_art",
        role: "accent",
        title: "Abstract black/white prints",
        description:
          "Чёткие линии, добавляют графичность и балансируют тёплое дерево.",
        style: "modern",
        palette: "monochrome",
        material: "paper + frame",
        importance: 3,
        zone: "decor",
        products: [],
      },
    ],
  },
  {
    designId: "design-12",
    summary:
      "Лёгкая сканди-гостиная с большим окном и растениями. Пространство дышит, минимум предметов, максимум света.",
    difficulty: "easy",
    mainStyle: "scandinavian",
    keyPoints: [
      "Большое окно + лёгкие шторы",
      "Растения как основной цветовой акцент",
      "Светлый диван и ковёр объединяют зону",
    ],
    items: [
      {
        id: "d12-sofa",
        category: "sofa",
        role: "primary",
        title: "Light scandi sofa",
        description:
          "Прямые линии, светлый текстиль, компактный размер для небольших гостиных.",
        style: "scandinavian",
        palette: "neutral",
        material: "textile",
        importance: 1,
        zone: "seating",
        products: [],
      },
      {
        id: "d12-rug",
        category: "rug",
        role: "secondary",
        title: "Soft neutral rug",
        description:
          "Задаёт мягкую основу, отделяет посадку от остального пространства.",
        style: "minimal",
        palette: "neutral",
        material: "textile",
        importance: 2,
        zone: "textiles",
        products: [],
      },
      {
        id: "d12-plants",
        category: "decor",
        role: "accent",
        title: "Group of tall plants",
        description:
          "Главный цветовой акцент, создаёт ощущение свежести и жизни.",
        style: "boho",
        palette: "green",
        material: "foliage",
        importance: 3,
        zone: "decor",
        products: [],
      },
      {
        id: "d12-lamp",
        category: "floor_lamp",
        role: "accent",
        title: "Slim floor lamp",
        description:
          "Акцентный свет в вечернее время, не перегружает композицию днём.",
        style: "modern",
        palette: "warm",
        material: "metal",
        importance: 3,
        zone: "lighting",
        products: [],
      },
    ],
  },
];
