import type { Design } from "./types";

const baseParams = "?auto=format&fit=crop&w=1400&q=85";

export const mockDesigns: Design[] = [
  {
    id: "d1",
    title: "Warm Japandi Living",
    src: `https://images.unsplash.com/photo-1505693416388-ac5ce068fe85${baseParams}`,
    style: "japandi",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "normal",
    material: "wood",
    theme: "japandi",
    composition: "centered",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 86,
  },
  {
    id: "d2",
    title: "Minimal Balcony Retreat",
    src: `https://images.unsplash.com/photo-1522708323590-d24dbb6b0267${baseParams}`,
    style: "minimal",
    room: "balcony",
    palette: "cool",
    budget: "low",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 78,
  },
  {
    id: "d3",
    title: "Industrial Loft Lounge",
    src: `https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e${baseParams}`,
    style: "industrial",
    room: "living_room",
    palette: "neutral",
    budget: "premium",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "concrete",
    theme: "industrial",
    composition: "open_space",
    dominantColor: "grey",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 92,
  },
  {
    id: "d4",
    title: "Boho Cozy Bedroom",
    src: `https://images.unsplash.com/photo-1523419400524-2231fcd53038${baseParams}`,
    style: "boho",
    room: "bedroom",
    palette: "warm",
    budget: "medium",
    lighting: "dim",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "boho",
    composition: "sectional",
    dominantColor: "brown",
    windowPresence: "no",
    plantPresence: "yes",
    flooring: "carpet",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 74,
  },
  {
    id: "d5",
    title: "Scandi Kitchen Light",
    src: `https://images.unsplash.com/photo-1505693415763-3e1b2e1a1402${baseParams}`,
    style: "scandinavian",
    room: "kitchen",
    palette: "cool",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "wood",
    theme: "scandinavian",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 88,
  },
  {
    id: "d6",
    title: "Retro Office Nook",
    src: `https://images.unsplash.com/photo-1529429617124-aee7c5cdaa5a${baseParams}`,
    style: "retro",
    room: "office",
    palette: "neutral",
    budget: "low",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "wood",
    theme: "modern",
    composition: "sectional",
    dominantColor: "brown",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "carpet",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 70,
  },
  {
    id: "d7",
    title: "Japandi Calm Bedroom",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}`,
    style: "japandi",
    room: "bedroom",
    palette: "neutral",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "minimal",
    material: "wood",
    theme: "japandi",
    composition: "centered",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 84,
  },
  {
    id: "d8",
    title: "Modern Open Bathroom",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&sat=-20`,
    style: "modern",
    room: "bathroom",
    palette: "monochrome",
    budget: "premium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "stone",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 90,
  },
  {
    id: "d9",
    title: "Loft Kitchen Concrete",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&h=800`,
    style: "loft",
    room: "kitchen",
    palette: "cool",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "normal",
    material: "concrete",
    theme: "industrial",
    composition: "open_space",
    dominantColor: "grey",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 81,
  },
  {
    id: "d10",
    title: "Minimal Hallway",
    src: `https://images.unsplash.com/photo-1523413651479-597eb2da0ad6${baseParams}`,
    style: "minimal",
    room: "hallway",
    palette: "monochrome",
    budget: "low",
    lighting: "dim",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "modern",
    composition: "centered",
    dominantColor: "black",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 69,
  },
  {
    id: "d11",
    title: "Scandi Living Green",
    src: `https://images.unsplash.com/photo-1505691723518-36a5ac3be353${baseParams}`,
    style: "scandinavian",
    room: "living_room",
    palette: "neutral",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "normal",
    material: "fabric",
    theme: "scandinavian",
    composition: "sectional",
    dominantColor: "green",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 85,
  },
  {
    id: "d12",
    title: "Industrial Office Dark",
    src: `https://images.unsplash.com/photo-1484156818044-c040038b0710${baseParams}`,
    style: "industrial",
    room: "office",
    palette: "cool",
    budget: "medium",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "metal",
    theme: "industrial",
    composition: "asymmetrical",
    dominantColor: "black",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 77,
  },
  {
    id: "d13",
    title: "Classic Bedroom Beige",
    src: `https://images.unsplash.com/photo-1484100356142-db6ab6244067${baseParams}`,
    style: "classic",
    room: "bedroom",
    palette: "neutral",
    budget: "premium",
    lighting: "mixed",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "classic",
    composition: "centered",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "carpet",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 83,
  },
  {
    id: "d14",
    title: "Boho Living Plants",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&sat=30`,
    style: "boho",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "boho",
    composition: "sectional",
    dominantColor: "green",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 80,
  },
  {
    id: "d15",
    title: "Minimal Bathroom Mono",
    src: `https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e${baseParams}&sat=-40`,
    style: "minimal",
    room: "bathroom",
    palette: "monochrome",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "stone",
    theme: "modern",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 82,
  },
  {
    id: "d16",
    title: "Retro Kitchen Blue",
    src: `https://images.unsplash.com/photo-1462396881884-de2c07cb95ed${baseParams}`,
    style: "retro",
    room: "kitchen",
    palette: "cool",
    budget: "low",
    lighting: "bright",
    furnitureDensity: "normal",
    material: "tile",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "blue",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 73,
  },
  {
    id: "d17",
    title: "Modern Office Glass",
    src: `https://images.unsplash.com/photo-1523419400524-2231fcd53038${baseParams}&sat=-10`,
    style: "modern",
    room: "office",
    palette: "neutral",
    budget: "premium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "modern",
    composition: "open_space",
    dominantColor: "grey",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 91,
  },
  {
    id: "d18",
    title: "Japandi Entryway",
    src: `https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e${baseParams}&fit=crop`,
    style: "japandi",
    room: "hallway",
    palette: "neutral",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "minimal",
    material: "wood",
    theme: "japandi",
    composition: "centered",
    dominantColor: "beige",
    windowPresence: "no",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 79,
  },
  {
    id: "d19",
    title: "Industrial Balcony",
    src: `https://images.unsplash.com/photo-1522708323590-d24dbb6b0267${baseParams}&sat=-15`,
    style: "industrial",
    room: "balcony",
    palette: "cool",
    budget: "low",
    lighting: "mixed",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "industrial",
    composition: "asymmetrical",
    dominantColor: "grey",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 68,
  },
  {
    id: "d20",
    title: "Boho Bathroom Plants",
    src: `https://images.unsplash.com/photo-1484154218962-a197022b5858${baseParams}`,
    style: "boho",
    room: "bathroom",
    palette: "warm",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "normal",
    material: "stone",
    theme: "boho",
    composition: "sectional",
    dominantColor: "green",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "tile",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 76,
  },
  {
    id: "d21",
    title: "Minimal Living Mono",
    src: `https://images.unsplash.com/photo-1523419400524-2231fcd53038${baseParams}&grayscale`,
    style: "minimal",
    room: "living_room",
    palette: "monochrome",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "fabric",
    theme: "modern",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 83,
  },
  {
    id: "d22",
    title: "Retro Living Bold",
    src: `https://images.unsplash.com/photo-1523419400524-2231fcd53038${baseParams}&sat=50`,
    style: "retro",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "brown",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 75,
  },
  {
    id: "d23",
    title: "Scandi Balcony Soft",
    src: `https://images.unsplash.com/photo-1484156818044-c040038b0710${baseParams}&sat=10`,
    style: "scandinavian",
    room: "balcony",
    palette: "neutral",
    budget: "low",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "wood",
    theme: "scandinavian",
    composition: "centered",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 72,
  },
  {
    id: "d24",
    title: "Industrial Kitchen Dark",
    src: `https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e${baseParams}&contrast=20`,
    style: "industrial",
    room: "kitchen",
    palette: "cool",
    budget: "medium",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "metal",
    theme: "industrial",
    composition: "open_space",
    dominantColor: "black",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 82,
  },
  {
    id: "d25",
    title: "Japandi Bathroom Calm",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&h=1000`,
    style: "japandi",
    room: "bathroom",
    palette: "neutral",
    budget: "premium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "stone",
    theme: "japandi",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 89,
  },
  {
    id: "d26",
    title: "Classic Living Art",
    src: `https://images.unsplash.com/photo-1505691723518-36a5ac3be353${baseParams}&sat=15`,
    style: "classic",
    room: "living_room",
    palette: "warm",
    budget: "premium",
    lighting: "mixed",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "classic",
    composition: "sectional",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 87,
  },
  {
    id: "d27",
    title: "Minimal Office White",
    src: `https://images.unsplash.com/photo-1523413651479-597eb2da0ad6${baseParams}&sat=-5`,
    style: "minimal",
    room: "office",
    palette: "monochrome",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "modern",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 80,
  },
  {
    id: "d28",
    title: "Retro Bathroom Color",
    src: `https://images.unsplash.com/photo-1484154218962-a197022b5858${baseParams}&sat=40`,
    style: "retro",
    room: "bathroom",
    palette: "warm",
    budget: "low",
    lighting: "bright",
    furnitureDensity: "normal",
    material: "tile",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "blue",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 71,
  },
  {
    id: "d29",
    title: "Industrial Hallway",
    src: `https://images.unsplash.com/photo-1484156818044-c040038b0710${baseParams}&h=900`,
    style: "industrial",
    room: "hallway",
    palette: "neutral",
    budget: "medium",
    lighting: "dim",
    furnitureDensity: "minimal",
    material: "concrete",
    theme: "industrial",
    composition: "centered",
    dominantColor: "grey",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 74,
  },
  {
    id: "d30",
    title: "Boho Balcony Lounge",
    src: `https://images.unsplash.com/photo-1522708323590-d24dbb6b0267${baseParams}&sat=25`,
    style: "boho",
    room: "balcony",
    palette: "warm",
    budget: "low",
    lighting: "mixed",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "boho",
    composition: "sectional",
    dominantColor: "brown",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 73,
  },
  {
    id: "d31",
    title: "Scandi Office Calm",
    src: `https://images.unsplash.com/photo-1529429617124-aee7c5cdaa5a${baseParams}&sat=-20`,
    style: "scandinavian",
    room: "office",
    palette: "cool",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "normal",
    material: "wood",
    theme: "scandinavian",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 82,
  },
  {
    id: "d32",
    title: "Modern Bedroom Mono",
    src: `https://images.unsplash.com/photo-1484100356142-db6ab6244067${baseParams}&grayscale=1`,
    style: "modern",
    room: "bedroom",
    palette: "monochrome",
    budget: "premium",
    lighting: "dim",
    furnitureDensity: "minimal",
    material: "fabric",
    theme: "modern",
    composition: "centered",
    dominantColor: "black",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "carpet",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 88,
  },
  {
    id: "d33",
    title: "Loft Living Brick",
    src: `https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e${baseParams}&sat=5`,
    style: "loft",
    room: "living_room",
    palette: "neutral",
    budget: "premium",
    lighting: "mixed",
    furnitureDensity: "normal",
    material: "brick",
    theme: "industrial",
    composition: "open_space",
    dominantColor: "brown",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 90,
  },
  {
    id: "d34",
    title: "Minimal Balcony Mono",
    src: `https://images.unsplash.com/photo-1484156818044-c040038b0710${baseParams}&grayscale`,
    style: "minimal",
    room: "balcony",
    palette: "monochrome",
    budget: "low",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "grey",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 71,
  },
  {
    id: "d35",
    title: "Classic Hallway",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&contrast=15`,
    style: "classic",
    room: "hallway",
    palette: "warm",
    budget: "medium",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "wood",
    theme: "classic",
    composition: "centered",
    dominantColor: "brown",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 78,
  },
  {
    id: "d36",
    title: "Boho Bedroom Art",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&sat=60`,
    style: "boho",
    room: "bedroom",
    palette: "warm",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "boho",
    composition: "sectional",
    dominantColor: "brown",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "carpet",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 77,
  },
  {
    id: "d37",
    title: "Industrial Office Brick",
    src: `https://images.unsplash.com/photo-1523413651479-597eb2da0ad6${baseParams}&contrast=10`,
    style: "industrial",
    room: "office",
    palette: "neutral",
    budget: "medium",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "brick",
    theme: "industrial",
    composition: "asymmetrical",
    dominantColor: "brown",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 79,
  },
  {
    id: "d38",
    title: "Japandi Living Mono",
    src: `https://images.unsplash.com/photo-1522708323590-d24dbb6b0267${baseParams}&grayscale`,
    style: "japandi",
    room: "living_room",
    palette: "monochrome",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "minimal",
    material: "wood",
    theme: "japandi",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 83,
  },
  {
    id: "d39",
    title: "Scandi Bathroom Soft",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&blur=1`,
    style: "scandinavian",
    room: "bathroom",
    palette: "neutral",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "stone",
    theme: "scandinavian",
    composition: "centered",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 81,
  },
  {
    id: "d40",
    title: "Modern Balcony Green",
    src: `https://images.unsplash.com/photo-1505693415763-3e1b2e1a1402${baseParams}&sat=15`,
    style: "modern",
    room: "balcony",
    palette: "cool",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "green",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 78,
  },
  {
    id: "d41",
    title: "Industrial Bedroom Dark",
    src: `https://images.unsplash.com/photo-1529429617124-aee7c5cdaa5a${baseParams}&h=1100`,
    style: "industrial",
    room: "bedroom",
    palette: "cool",
    budget: "premium",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "concrete",
    theme: "industrial",
    composition: "sectional",
    dominantColor: "grey",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 85,
  },
  {
    id: "d42",
    title: "Boho Office Light",
    src: `https://images.unsplash.com/photo-1484101403633-1c974e09a2c9${baseParams}&sat=20`,
    style: "boho",
    room: "office",
    palette: "warm",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "normal",
    material: "fabric",
    theme: "boho",
    composition: "sectional",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 79,
  },
  {
    id: "d43",
    title: "Scandi Kitchen Neutral",
    src: `https://images.unsplash.com/photo-1505693415763-3e1b2e1a1402${baseParams}&sat=-5`,
    style: "scandinavian",
    room: "kitchen",
    palette: "neutral",
    budget: "medium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "wood",
    theme: "scandinavian",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 86,
  },
  {
    id: "d44",
    title: "Retro Living Colorful",
    src: `https://images.unsplash.com/photo-1462396881884-de2c07cb95ed${baseParams}&sat=60`,
    style: "retro",
    room: "living_room",
    palette: "warm",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "cluttered",
    material: "fabric",
    theme: "modern",
    composition: "asymmetrical",
    dominantColor: "blue",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 76,
  },
  {
    id: "d45",
    title: "Minimal Office Narrow",
    src: `https://images.unsplash.com/photo-1523413651479-597eb2da0ad6${baseParams}&h=950`,
    style: "minimal",
    room: "office",
    palette: "neutral",
    budget: "low",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "modern",
    composition: "centered",
    dominantColor: "white",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "no",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 74,
  },
  {
    id: "d46",
    title: "Industrial Bathroom Brick",
    src: `https://images.unsplash.com/photo-1484154218962-a197022b5858${baseParams}&contrast=15`,
    style: "industrial",
    room: "bathroom",
    palette: "neutral",
    budget: "medium",
    lighting: "dim",
    furnitureDensity: "normal",
    material: "brick",
    theme: "industrial",
    composition: "centered",
    dominantColor: "brown",
    windowPresence: "no",
    plantPresence: "no",
    flooring: "tile",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 80,
  },
  {
    id: "d47",
    title: "Japandi Kitchen Warm",
    src: `https://images.unsplash.com/photo-1522708323590-d24dbb6b0267${baseParams}&sat=5`,
    style: "japandi",
    room: "kitchen",
    palette: "warm",
    budget: "medium",
    lighting: "mixed",
    furnitureDensity: "minimal",
    material: "wood",
    theme: "japandi",
    composition: "sectional",
    dominantColor: "beige",
    windowPresence: "yes",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 84,
  },
  {
    id: "d48",
    title: "Boho Hallway Art",
    src: `https://images.unsplash.com/photo-1505691938895-1758d7feb511${baseParams}&sat=35`,
    style: "boho",
    room: "hallway",
    palette: "warm",
    budget: "low",
    lighting: "dim",
    furnitureDensity: "cluttered",
    material: "wood",
    theme: "boho",
    composition: "centered",
    dominantColor: "brown",
    windowPresence: "no",
    plantPresence: "yes",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "portrait",
    orientation: "vertical",
    qualityScore: 70,
  },
  {
    id: "d49",
    title: "Modern Bedroom Glass",
    src: `https://images.unsplash.com/photo-1484100356142-db6ab6244067${baseParams}&sat=-25`,
    style: "modern",
    room: "bedroom",
    palette: "cool",
    budget: "premium",
    lighting: "bright",
    furnitureDensity: "minimal",
    material: "glass",
    theme: "modern",
    composition: "centered",
    dominantColor: "blue",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "wood",
    artPresence: "yes",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 89,
  },
  {
    id: "d50",
    title: "Industrial Balcony Night",
    src: `https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e${baseParams}&sat=-30`,
    style: "industrial",
    room: "balcony",
    palette: "cool",
    budget: "premium",
    lighting: "dim",
    furnitureDensity: "minimal",
    material: "metal",
    theme: "industrial",
    composition: "asymmetrical",
    dominantColor: "black",
    windowPresence: "yes",
    plantPresence: "no",
    flooring: "concrete",
    artPresence: "no",
    aspectRatio: "landscape",
    orientation: "horizontal",
    qualityScore: 82,
  },
];
