import type { DesignImage } from "./types";

export const mockDesigns: DesignImage[] = [
  {
    id: "1",
    title: "Minimal Scandinavian Living Room",
    src: "https://images.unsplash.com/photo-1523419400524-2231fcd53038?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "scandinavian",
    roomType: "living_room",
    colorPalette: "cool",
    budget: "medium",
  },
  {
    id: "2",
    title: "Warm Loft Bedroom",
    src: "https://images.unsplash.com/photo-1484101403633-1c974e09a2c9?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "loft",
    roomType: "bedroom",
    colorPalette: "warm",
    budget: "high",
  },
  {
    id: "3",
    title: "Cozy Minimal Kitchen",
    src: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "minimal",
    roomType: "kitchen",
    colorPalette: "warm",
    budget: "medium",
  },
  {
    id: "4",
    title: "Modern Living Room",
    src: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "minimal",
    roomType: "living_room",
    colorPalette: "cool",
    budget: "medium",
  },
  {
    id: "5",
    title: "Soft Tones Bedroom",
    src: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "scandinavian",
    roomType: "bedroom",
    colorPalette: "warm",
    budget: "low",
  },
  {
    id: "6",
    title: "Industrial Loft",
    src: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "loft",
    roomType: "living_room",
    colorPalette: "cool",
    budget: "high",
  },
  {
    id: "7",
    title: "Bright Kitchen",
    src: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "minimal",
    roomType: "kitchen",
    colorPalette: "cool",
    budget: "medium",
  },
  {
    id: "8",
    title: "Urban Bedroom",
    src: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "loft",
    roomType: "bedroom",
    colorPalette: "cool",
    budget: "medium",
  },
  {
    id: "9",
    title: "Nordic Living",
    src: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "scandinavian",
    roomType: "living_room",
    colorPalette: "warm",
    budget: "low",
  },
  {
    id: "10",
    title: "Compact Studio",
    src: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "minimal",
    roomType: "living_room",
    colorPalette: "cool",
    budget: "low",
  },
  {
    id: "11",
    title: "Soft Loft Kitchen",
    src: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "loft",
    roomType: "kitchen",
    colorPalette: "warm",
    budget: "medium",
  },
  {
    id: "12",
    title: "Calm Bedroom",
    src: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85",
    source: "mock",
    style: "scandinavian",
    roomType: "bedroom",
    colorPalette: "cool",
    budget: "medium",
  },
];
